version: '3'

networks:
  distributed-proxy:
    driver: bridge

services:

  distributed-events-db:
    image: 'library/postgres:latest'
    container_name: distributed-events-db
    env_file:
      - database.env
    restart: always
    networks:
      - distributed-proxy
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - distributed-proxy

  go-distributed-events-producer:
    build:
      context: ../producer
      dockerfile: .Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - distributed-events-db
      - rabbitmq
    restart: unless-stopped
    networks:
      - distributed-proxy

  go-distributed-events-consumer:
    build:
      context: ../consumer
      dockerfile: .Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - distributed-events-db
      - rabbitmq
      - go-distributed-events-producer
    restart: unless-stopped
    networks:
      - distributed-proxy